### PR TITLE
redefined whole project with python style-guide, added features, ~Bhavik""

### PR DESCRIPTION
**Pull request by MarlonJD**
teamCandle/candle-python#3

### CODE REVIEW

**Comment by majdbousaad** [comment]
README.md has to be changed back to @MarlonJD changes

**Comment by majdbousaad** [comment]
Now I am waiting for all reviews from you ^^

**Comment by MarlonJD** [comment]
I think we should merge and make changes. Prepare Readme for contribute others. Now we're only 4 people.  We should reach more people and not to rush about the coding. After contribution that everyone make, we'll start some rules about the commit text, comments, pull request etc. I revert these changes for my fault but now we cannot merge new changes from python_dev. What about your idea about these?

> Some changes must be made.
> 
> 1. For encapsulation, Classes members must be private.
> 2. Since Candle.py was changed to candle.py, import statement must me changed in candle_test.py
> 3. Since Files structure has been changed, the changes must be reflected to README.md file.
>    Regards,
>    Majd Bousaad

**Comment by majdbousaad** [comment]
@MarlonJD 
Let's now merge this branch into `master` since I made the changes, then we will remove all branches other than `master`, finally we create a new branch named `dev`
What do you think?

**Comment by MarlonJD** [comment]
Agreed :+1:

**Comment by bhavik-knight** [comment]
I disagree with removing all branches other than master.
Let other branches be! And make all branch up to date with master if that's possible!

**Pull request merged**
